server {
    listen 80 default_server;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        try_files /index.html =404;
        return 404;
    }

    error_page 404 /index.html;

    location = /index.html {
        root /usr/share/nginx/html;
        internal;
    }
}
